import json

def convert_json_to_dict(json_data):
    result_dict = {}

    for obj in json_data:
        code = obj.get("Code", "")
        if code is not None:
            code = code.strip()
        feldbezeichnung = obj.get("Feldbezeichnung", "")

        if code and feldbezeichnung:
            result_dict[code] = feldbezeichnung

    return result_dict

json_data = [
    {
        "Category": "Werte / Zusatzdaten",
        "Code": "K0001",
        "qs-STAT Pflicht-eingabe-felder": None,
        "Schl\u00fcs-selfeld \nim upload": None,
        "Bemerkung": None,
        "Format-Vorgabe,\nBeispiele": None,
        "Standard allgemein": "keine Vorgabe",
        "Sonderkonfigurationen / Hinweise": None,
        "L\u00e4nge": 22,
        "Typ*": "F",
        "Eingabe": None,
        "Bemerkung.1": None
    },
    {
        "Category": None,
        "Code": "K0002",
        "qs-STAT Pflicht-eingabe-felder": None,
        "Schl\u00fcs-selfeld \nim upload": None,
        "Feldbezeichnung": "Attribut",
        "Bemerkung": "g\u00fcltiger / ung\u00fcltiger Messwert",
        "Format-Vorgabe,\nBeispiele": None,
        "Standard allgemein": "keine Vorgabe",
        "Sonderkonfigurationen / Hinweise": None,
        "L\u00e4nge": 5,
        "Typ*": "I",
        "Eingabe": None,
        "Bemerkung.1": None
    },
    {
        "Category": None,
        "Code": "K0004",
        "qs-STAT Pflicht-eingabe-felder": None,
        "Schl\u00fcs-selfeld \nim upload": None,
        "Feldbezeichnung": "Datum/Zeit",
        "Bemerkung": None,
        "Format-Vorgabe,\nBeispiele": None,
        "Standard allgemein": "keine Vorgabe",
        "Sonderkonfigurationen / Hinweise": None,
        "L\u00e4nge": "---",
        "Typ*": "D",
        "Eingabe": None,
        "Bemerkung.1": None
    },
    {
        "Category": None,
        "Code": "K0005",
        "qs-STAT Pflicht-eingabe-felder": None,
        "Schl\u00fcs-selfeld \nim upload": None,
        "Feldbezeichnung": "Ereignis",
        "Bemerkung": "wird verwendet f\u00fcr die Ma\u00dfnahmenaufnhame\nKatalog siehe K2060",
        "Format-Vorgabe,\nBeispiele": None,
        "Standard allgemein": "aus Katalogauswahl",
        "Sonderkonfigurationen / Hinweise": None,
        "L\u00e4nge": "---",
        "Typ*": "S",
        "Eingabe": None,
        "Bemerkung.1": None
    },
    {
        "Category": None,
        "Code": "K0006",
        "qs-STAT Pflicht-eingabe-felder": "X",
        "Schl\u00fcs-selfeld \nim upload": None,
        "Feldbezeichnung": "Chargennummer",
        "Bemerkung": "siehe z.B. Chargenbegleitschein",
        "Format-Vorgabe,\nBeispiele": 12130,
        "Standard allgemein": "Chargennummer",
        "Sonderkonfigurationen / Hinweise": None,
        "L\u00e4nge": 20,
        "Typ*": "A",
        "Eingabe": None,
        "Bemerkung.1": None
    },
    {
        "Category": None,
        "Code": "K0007",
        "qs-STAT Pflicht-eingabe-felder": None,
        "Schl\u00fcs-selfeld \nim upload": None,
        "Feldbezeichnung": "Nestnummer",
        "Bemerkung": "Katalogbasiert",
        "Format-Vorgabe,\nBeispiele": None,
        "Standard allgemein": "keine Vorgabe",
        "Sonderkonfigurationen / Hinweise": None,
        "L\u00e4nge": 10,
        "Typ*": "I",
        "Eingabe": None,
        "Bemerkung.1": None
    },
    {
        "Category": None,
        "Code": "K0008",
        "qs-STAT Pflicht-eingabe-felder": None,
        "Schl\u00fcs-selfeld \nim upload": None,
        "Feldbezeichnung": "Pr\u00fcfername",
        "Bemerkung": "Katalogbasiert",
        "Format-Vorgabe,\nBeispiele": None,
        "Standard allgemein": "aus Katalogauswahl",
        "Sonderkonfigurationen / Hinweise": None,
        "L\u00e4nge": 10,
        "Typ*": "I",
        "Eingabe": None,
        "Bemerkung.1": None
    },
    {
        "Category": None,
        "Code": "K0009",
        "qs-STAT Pflicht-eingabe-felder": None,
        "Schl\u00fcs-selfeld \nim upload": None,
        "Feldbezeichnung": "Textfeld",
        "Bemerkung": "freie Texteingabe",
        "Format-Vorgabe,\nBeispiele": "Granulatwechsel\nDMC nach vorne",
        "Standard allgemein": "keine Vorgabe",
        "Sonderkonfigurationen / Hinweise": "aktiv in DB gesetzt",
        "L\u00e4nge": 40,
        "Typ*": "A",
        "Eingabe": None,
        "Bemerkung.1": None
    },
    {
        "Category": None,
        "Code": "K0010",
        "qs-STAT Pflicht-eingabe-felder": None,
        "Schl\u00fcs-selfeld \nim upload": None,
        "Feldbezeichnung": "Maschine",
        "Bemerkung": "Katalogbasiert",
        "Format-Vorgabe,\nBeispiele": None,
        "Standard allgemein": "ggf. Vorbearbeitsmaschine",
        "Sonderkonfigurationen / Hinweise": None,
        "L\u00e4nge": 10,
        "Typ*": "I",
        "Eingabe": None,
        "Bemerkung.1": None
    },
    {
        "Category": None,
        "Code": "K0011",
        "qs-STAT Pflicht-eingabe-felder": None,
        "Schl\u00fcs-selfeld \nim upload": None,
        "Feldbezeichnung": "Prozessparameter",
        "Bemerkung": "Katalog siehe K2061",
        "Format-Vorgabe,\nBeispiele": None,
        "Standard allgemein": "keine Vorgabe",
        "Sonderkonfigurationen / Hinweise": None,
        "L\u00e4nge": "---",
        "Typ*": "S",
        "Eingabe": None,
        "Bemerkung.1": None
    },
    {
        "Category": None,
        "Code": "K0012",
        "qs-STAT Pflicht-eingabe-felder": None,
        "Schl\u00fcs-selfeld \nim upload": None,
        "Feldbezeichnung": "Pr\u00fcfmittelnummer",
        "Bemerkung": "Integer der auf den Katalog verweist\nz.B. 005_ZEISS_01  hat die Pr\u00fcfmittelnummer 7",
        "Format-Vorgabe,\nBeispiele": None,
        "Standard allgemein": "aus Katalogauswahl",
        "Sonderkonfigurationen / Hinweise": None,
        "L\u00e4nge": 10,
        "Typ*": "I",
        "Eingabe": None,
        "Bemerkung.1": None
    },
    {
        "Category": None,
        "Code": "K0014",
        "qs-STAT Pflicht-eingabe-felder": "X",
        "Schl\u00fcs-selfeld \nim upload": None,
        "Feldbezeichnung": "Teileident",
        "Bemerkung": "z.B. eingescannter DMC Code",
        "Format-Vorgabe,\nBeispiele": "1129xxxxxxx",
        "Standard allgemein": "z.B. DMC Code",
        "Sonderkonfigurationen / Hinweise": "aktiv in DB gesetzt",
        "L\u00e4nge": 40,
        "Typ*": "A",
        "Eingabe": None,
        "Bemerkung.1": None
    },
    {
        "Category": None,
        "Code": "K0016",
        "qs-STAT Pflicht-eingabe-felder": None,
        "Schl\u00fcs-selfeld \nim upload": None,
        "Feldbezeichnung": "Produktionsnummer",
        "Bemerkung": "Inhalt wird von K1005 in K0016 geschiftet.\nDamit wird die Ordnerstruktur f\u00fcr die CMM Ablage erstellt ",
        "Format-Vorgabe,\nBeispiele": None,
        "Standard allgemein": None,
        "Sonderkonfigurationen / Hinweise": None,
        "L\u00e4nge": 30,
        "Typ*": "A",
        "Eingabe": None,
        "Bemerkung.1": None
    },
    {
        "Category": None,
        "Code": "K0017",
        "qs-STAT Pflicht-eingabe-felder": None,
        "Schl\u00fcs-selfeld \nim upload": None,
        "Feldbezeichnung": "Werkst\u00fccktr\u00e4gernummer",
        "Bemerkung": "Inhalt wird von K1082 in K0017 geschiftet.\nDamit wird die Ordnerstruktur f\u00fcr die CMM Ablage erstellt ",
        "Format-Vorgabe,\nBeispiele": None,
        "Standard allgemein": None,
        "Sonderkonfigurationen / Hinweise": None,
        "L\u00e4nge": 30,
        "Typ*": "A",
        "Eingabe": None,
        "Bemerkung.1": None
    },
    {
        "Category": None,
        "Code": "K0053",
        "qs-STAT Pflicht-eingabe-felder": None,
        "Schl\u00fcs-selfeld \nim upload": None,
        "Feldbezeichnung": "Auftrag",
        "Bemerkung": "siehe z.B. Chargenbegleitschein",
        "Format-Vorgabe,\nBeispiele": None,
        "Standard allgemein": "keine Vorgabe",
        "Sonderkonfigurationen / Hinweise": None,
        "L\u00e4nge": 20,
        "Typ*": "A",
        "Eingabe": None,
        "Bemerkung.1": None
    },
    {
        "Category": "Anzahl Merkmale",
        "Code": "K0100",
        "qs-STAT Pflicht-eingabe-felder": None,
        "Schl\u00fcs-selfeld \nim upload": None,
        "Feldbezeichnung": "Anzahl Merkmale in Datei",
        "Bemerkung": None,
        "Format-Vorgabe,\nBeispiele": None,
        "Standard allgemein": None,
        "Sonderkonfigurationen / Hinweise": None,
        "L\u00e4nge": 5,
        "Typ*": "I",
        "Eingabe": None,
        "Bemerkung.1": None
    },
    {
        "Category": "Teiledaten",
        "Code": "K1001",
        "qs-STAT Pflicht-eingabe-felder": "X",
        "Schl\u00fcs-selfeld \nim upload": "X",
        "Feldbezeichnung": "Teilenummer",
        "Bemerkung": "Eingabe der SachNr. \nDaten werden durch \"_\" getrennt, keine Leerzeichen",
        "Format-Vorgabe,\nBeispiele": "1_461_C46_005",
        "Standard allgemein": "1_461_C46_005\nPulldown Menue an Messmaschine",
        "Sonderkonfigurationen / Hinweise": None,
        "L\u00e4nge": 30,
        "Typ*": "A",
        "Eingabe": "Auswahlmaske",
        "Bemerkung.1": None
    },
    {
        "Category": None,
        "Code": "K1002",
        "qs-STAT Pflicht-eingabe-felder": "X",
        "Schl\u00fcs-selfeld \nim upload": "X",
        "Feldbezeichnung": "Teilebezeichnung",
        "Bemerkung": "Teilebezeichnung\nName ausgeschrieben",
        "Format-Vorgabe,\nBeispiele": "Rollenschuh",
        "Standard allgemein": "Teilespezifisch eindeutig und durchg\u00e4ngig.\nKatalogauswahl an Messmaschine",
        "Sonderkonfigurationen / Hinweise": None,
        "L\u00e4nge": 80,
        "Typ*": "A",
        "Eingabe": "Fest",
        "Bemerkung.1": "Editierung muss m\u00f6glich sein"
    },
    {
        "Category": None,
        "Code": "K1003",
        "qs-STAT Pflicht-eingabe-felder": None,
        "Schl\u00fcs-selfeld \nim upload": None,
        "Feldbezeichnung": "Teilekurzbezeichnung",
        "Bemerkung": "Feld wird als Sortierfeld der VE Montage und VE Teilefertigung verwendet",
        "Format-Vorgabe,\nBeispiele": "VE Montage",
        "Standard allgemein": None,
        "Sonderkonfigurationen / Hinweise": None,
        "L\u00e4nge": None,
        "Typ*": None,
        "Eingabe": None,
        "Bemerkung.1": None
    },
    {
        "Category": None,
        "Code": "K1004",
        "qs-STAT Pflicht-eingabe-felder": "X",
        "Schl\u00fcs-selfeld \nim upload": "X",
        "Feldbezeichnung": "\u00c4nderungsstand d. Teils",
        "Bemerkung": "\u00c4nderungsverfolgung von Zeichnungs\u00e4nderungen, Details k\u00f6nnen in K1900 eingetragen werden\nFormat: TT.MM.JJJJ\nZeiss: NN_JJJJMMTT",
        "Format-Vorgabe,\nBeispiele": "07.03.2011\n\nZeiss: 04_20100215",
        "Standard allgemein": "Zeiss: NN_JJJJMMTT\nMahr: TT.MM.JJ\nHommel: TT.MM.JJJJ\nFMS1000: TT.MM.JJJJ\nZygolot: \u2026",
        "Sonderkonfigurationen / Hinweise": "Sonderregelung Nockenwelle f\u00fcr Hommel W55: wird als Feld f\u00fcr DMC-Codeverwendet",
        "L\u00e4nge": 20,
        "Typ*": "A",
        "Eingabe": "Fest",
        "Bemerkung.1": "Editierung muss m\u00f6glich sein"
    },
    {
        "Category": None,
        "Code": "K1005",
        "qs-STAT Pflicht-eingabe-felder": "X",
        "Schl\u00fcs-selfeld \nim upload": None,
        "Feldbezeichnung": "Erzeugnis",
        "Bemerkung": "Benennung des Erzeugnisses\nInhalt wird in K0016 geschiftet.",
        "Format-Vorgabe,\nBeispiele": "CP4",
        "Standard allgemein": "CP4",
        "Sonderkonfigurationen / Hinweise": None,
        "L\u00e4nge": 40,
        "Typ*": "A",
        "Eingabe": "Fest",
        "Bemerkung.1": "Editierung muss m\u00f6glich sein"
    },
    {
        "Category": None,
        "Code": "K1017",
        "qs-STAT Pflicht-eingabe-felder": None,
        "Schl\u00fcs-selfeld \nim upload": None,
        "Feldbezeichnung": "Pr\u00fcfplan Freigabe",
        "Bemerkung": "Pr\u00fcfplan freigeben (0), sperren (nicht 0)\nNur in freigegebene Pr\u00fcfpl\u00e4nen k\u00f6nnen Werte eingegeben werden. \nBei Neuerstellung eines Pr\u00fcfplans ist ggf. der vorhandene alte Pr\u00fcfplan zu sperren",
        "Format-Vorgabe,\nBeispiele": None,
        "Standard allgemein": None,
        "Sonderkonfigurationen / Hinweise": None,
        "L\u00e4nge": None,
        "Typ*": "I",
        "Eingabe": None,
        "Bemerkung.1": None
    },
    {
        "Category": None,
        "Code": "K1081",
        "qs-STAT Pflicht-eingabe-felder": "X",
        "Schl\u00fcs-selfeld \nim upload": "X",
        "Feldbezeichnung": "Maschinen - Nummer",
        "Bemerkung": "Nummer der Maschine / Einrichtung / Nestnummer / Station\nZahlen sind zweistellig\nentweder doppelte Nennung der Maschinennummer oder, falls vorhanden, Unterscheidung der Einheiten in der Maschine\nTrennung der Informationen durch \"_\", \nggf. Nennung der Inv.-Nr.",
        "Format-Vorgabe,\nBeispiele": "EH_01, \u2026",
        "Standard allgemein": "EH_xx \n(pulldown-men\u00fc an Messmaschine)",
        "Sonderkonfigurationen / Hinweise": None,
        "L\u00e4nge": 20,
        "Typ*": "A",
        "Eingabe": "Auswahlmaske",
        "Bemerkung.1": None
    },
    {
        "Category": None,
        "Code": "K1082",
        "qs-STAT Pflicht-eingabe-felder": "X",
        "Schl\u00fcs-selfeld \nim upload": "X",
        "Feldbezeichnung": "Maschinen - Bezeichnung",
        "Bemerkung": "Bezeichnung der Maschine / Einrichtung\nMaschinenname mit laufender zweistelliger Nummer, Maschinenbezeichnung und Nummer durch \"_\" getrennt\nInhalt wird in K0017 geschiftet,",
        "Format-Vorgabe,\nBeispiele": "Bahmueller_01",
        "Standard allgemein": "vollst\u00e4ndiger Namen des Maschinenherstellers_2-stellige Maschinennummer\n(pulldown-men\u00fc an Messmaschine) \n(Achtung: \u00dc -> UE)",
        "Sonderkonfigurationen / Hinweise": None,
        "L\u00e4nge": 40,
        "Typ*": "A",
        "Eingabe": "Auswahlmaske",
        "Bemerkung.1": None
    },
    {
        "Category": None,
        "Code": "K1100",
        "qs-STAT Pflicht-eingabe-felder": "X",
        "Schl\u00fcs-selfeld \nim upload": None,
        "Feldbezeichnung": "Bereich",
        "Bemerkung": None,
        "Format-Vorgabe,\nBeispiele": None,
        "Standard allgemein": "FeP/MSC",
        "Sonderkonfigurationen / Hinweise": None,
        "L\u00e4nge": 40,
        "Typ*": "A",
        "Eingabe": "Fest",
        "Bemerkung.1": None
    },
    {
        "Category": None,
        "Code": "K1101",
        "qs-STAT Pflicht-eingabe-felder": "X",
        "Schl\u00fcs-selfeld \nim upload": None,
        "Feldbezeichnung": "Gruppe/Abteilung",
        "Bemerkung": None,
        "Format-Vorgabe,\nBeispiele": None,
        "Standard allgemein": "FeP/MSC4",
        "Sonderkonfigurationen / Hinweise": None,
        "L\u00e4nge": 40,
        "Typ*": "A",
        "Eingabe": "Fest",
        "Bemerkung.1": None
    },
    {
        "Category": None,
        "Code": "K1102",
        "qs-STAT Pflicht-eingabe-felder": "X",
        "Schl\u00fcs-selfeld \nim upload": None,
        "Feldbezeichnung": "Werkstatt/Bereich",
        "Bemerkung": None,
        "Format-Vorgabe,\nBeispiele": "W011270",
        "Standard allgemein": "jeweilige Werkstatt",
        "Sonderkonfigurationen / Hinweise": None,
        "L\u00e4nge": 40,
        "Typ*": "A",
        "Eingabe": "Fest",
        "Bemerkung.1": None
    },
    {
        "Category": None,
        "Code": "K1203",
        "qs-STAT Pflicht-eingabe-felder": "X",
        "Schl\u00fcs-selfeld \nim upload": "X",
        "Feldbezeichnung": "Pr\u00fcfgrund",
        "Bemerkung": "z.B. Serie, Sondermessung, Abnahme\nweitere Pr\u00fcfgr\u00fcnde in Absprache mit FeP/QMM11 Schneider, Funk",
        "Format-Vorgabe,\nBeispiele": "Serie\n2h-Messung\nAbnahme\nSondermessung\nKalibriermessung",
        "Standard allgemein": "Serie\n2h-Messung\nAbnahme\nSondermessung\nKalibriermessung",
        "Sonderkonfigurationen / Hinweise": None,
        "L\u00e4nge": None,
        "Typ*": None,
        "Eingabe": "Auswahlmaske",
        "Bemerkung.1": None
    },
    {
        "Category": None,
        "Code": "K1206",
        "qs-STAT Pflicht-eingabe-felder": "X",
        "Schl\u00fcs-selfeld \nim upload": "X",
        "Feldbezeichnung": "Pr\u00fcfplatz",
        "Bemerkung": "Pr\u00fcfpl\u00e4tze werdend durch FeP/QMM11 Schneider, Funk vergeben\nDie Unterscheidung der einzelnen Messpl\u00e4tze erfolgt \u00fcber das K-Feld K0012",
        "Format-Vorgabe,\nBeispiele": "001_RS-STOTZ\n002_NW-STOTZ\n003_PK-MIKROSA\n004_RS-NANOSCAN\n005_ZEISS\n006_FMS1000",
        "Standard allgemein": "Vorgabe durch QMM",
        "Sonderkonfigurationen / Hinweise": None,
        "L\u00e4nge": 40,
        "Typ*": "A",
        "Eingabe": "Fest",
        "Bemerkung.1": "Editierung muss m\u00f6glich sein"
    },
    {
        "Category": None,
        "Code": "K1207",
        "qs-STAT Pflicht-eingabe-felder": None,
        "Schl\u00fcs-selfeld \nim upload": None,
        "Feldbezeichnung": "Abt./Name",
        "Bemerkung": None,
        "Format-Vorgabe,\nBeispiele": None,
        "Standard allgemein": None,
        "Sonderkonfigurationen / Hinweise": None,
        "L\u00e4nge": 40,
        "Typ*": "A",
        "Eingabe": None,
        "Bemerkung.1": None
    },
    {
        "Category": None,
        "Code": "K1900",
        "qs-STAT Pflicht-eingabe-felder": None,
        "Schl\u00fcs-selfeld \nim upload": None,
        "Feldbezeichnung": "Kommentar",
        "Bemerkung": "Freitexteingabe\nkann z.B. n\u00e4here Informationen f\u00fcr \u00c4nderungen im K1004 enthalten",
        "Format-Vorgabe,\nBeispiele": None,
        "Standard allgemein": None,
        "Sonderkonfigurationen / Hinweise": None,
        "L\u00e4nge": 255,
        "Typ*": "A",
        "Eingabe": None,
        "Bemerkung.1": None
    },
    {
        "Category": "Merkmalsdaten",
        "Code": "K2001",
        "qs-STAT Pflicht-eingabe-felder": "X",
        "Schl\u00fcs-selfeld \nim upload": "X",
        "Feldbezeichnung": "Merkmal-Nr",
        "Bemerkung": "bei Zeiss-Messmaschinen nicht als Schl\u00fcsselfeld definiert\nNach M\u00f6glichkeit die Merkmalsnummern aus der Tabelle der Pr\u00fcfmerkmale (siehe TEF-Zeichnung) verwenden",
        "Format-Vorgabe,\nBeispiele": 1,
        "Standard allgemein": "siehe Zeichnung",
        "Sonderkonfigurationen / Hinweise": None,
        "L\u00e4nge": 20,
        "Typ*": "A",
        "Eingabe": "Fest",
        "Bemerkung.1": "Editierung muss m\u00f6glich sein"
    },
    {
        "Category": None,
        "Code": "K2002",
        "qs-STAT Pflicht-eingabe-felder": "X",
        "Schl\u00fcs-selfeld \nim upload": "X",
        "Feldbezeichnung": "Merkmal-Bez.",
        "Bemerkung": "Teilespezifisch eindeutig und durchg\u00e4ngig",
        "Format-Vorgabe,\nBeispiele": "Rz,\nAu\u00dfen-DMR",
        "Standard allgemein": "Teilespezifisch eindeutig und durchg\u00e4ngig.",
        "Sonderkonfigurationen / Hinweise": None,
        "L\u00e4nge": 80,
        "Typ*": "A",
        "Eingabe": "Fest",
        "Bemerkung.1": "Editierung muss m\u00f6glich sein"
    },
    {
        "Category": None,
        "Code": "K2004",
        "qs-STAT Pflicht-eingabe-felder": None,
        "Schl\u00fcs-selfeld \nim upload": None,
        "Feldbezeichnung": "Merkmalsart",
        "Bemerkung": "variabel, attributiv, \u2026",
        "Format-Vorgabe,\nBeispiele": None,
        "Standard allgemein": "-",
        "Sonderkonfigurationen / Hinweise": None,
        "L\u00e4nge": 1,
        "Typ*": "I",
        "Eingabe": None,
        "Bemerkung.1": None
    },
    {
        "Category": None,
        "Code": "K2005",
        "qs-STAT Pflicht-eingabe-felder": "X",
        "Schl\u00fcs-selfeld \nim upload": None,
        "Feldbezeichnung": "Merkmalsklasse",
        "Bemerkung": "Wird verwendet zur Unterscheidung von F\u00fchrungs- und Verfolgungsmerkmalen und Hilfsma\u00dfen\n\nDefinierte Feldinhalte\n4 -> SPC, F\u00fchrungsmerkmal\n3 -> signifikant\n2 -> wichtig, Verfolgungsmerkmal\n1 -> weniger wichtig\n0 -> unwichtig, Hilfsma\u00df",
        "Format-Vorgabe,\nBeispiele": "4\n3\n2\n1\n0",
        "Standard allgemein": "Definierte Feldinhalte\n4 -> SPC , F\u00fchrungsmerkmale\n3 -> signifikant\n2 -> wichtig, Verfolgungsmerkmal\n1 -> weniger wichtig\n0 -> unwichtig, Hilfsma\u00df\n------------------------\ndurchg\u00e4ngig f\u00fcr alle Messmaschinen, au\u00dfer Mahr",
        "Sonderkonfigurationen / Hinweise": "Umbenennung in\nTextdatenbank qdastext.mdb",
        "L\u00e4nge": 5,
        "Typ*": "I5",
        "Eingabe": "Fest",
        "Bemerkung.1": "Editierung muss m\u00f6glich sein"
    },
    {
        "Category": None,
        "Code": "K2006",
        "qs-STAT Pflicht-eingabe-felder": None,
        "Schl\u00fcs-selfeld \nim upload": None,
        "Feldbezeichnung": "Regelungsart\nUmbenannt: SF",
        "Bemerkung": "wird bei Bedarf bei einer genehmigten Sonderfreigabe durch den Planer markiert",
        "Format-Vorgabe,\nBeispiele": None,
        "Standard allgemein": "wird bei Bedarf bei einer genehmigten Sonderfreigabe durch den Planer markiert",
        "Sonderkonfigurationen / Hinweise": "Umbenennung in\nTextdatenbank qdastext.mdb",
        "L\u00e4nge": 1,
        "Typ*": "I",
        "Eingabe": None,
        "Bemerkung.1": None
    },
    {
        "Category": None,
        "Code": "K2009",
        "qs-STAT Pflicht-eingabe-felder": None,
        "Schl\u00fcs-selfeld \nim upload": None,
        "Feldbezeichnung": "Messgr\u00f6\u00dfe",
        "Bemerkung": None,
        "Format-Vorgabe,\nBeispiele": None,
        "Standard allgemein": None,
        "Sonderkonfigurationen / Hinweise": None,
        "L\u00e4nge": 3,
        "Typ*": "I",
        "Eingabe": None,
        "Bemerkung.1": None
    },
    {
        "Category": None,
        "Code": "K2016",
        "qs-STAT Pflicht-eingabe-felder": None,
        "Schl\u00fcs-selfeld \nim upload": None,
        "Feldbezeichnung": "100% Messung",
        "Bemerkung": "Kennzeichnung sofern es sich um ein Merkmal mit einer 100% Pr\u00fcfung handelt",
        "Format-Vorgabe,\nBeispiele": None,
        "Standard allgemein": None,
        "Sonderkonfigurationen / Hinweise": "ersetzt K2007 aus ME7",
        "L\u00e4nge": None,
        "Typ*": None,
        "Eingabe": None,
        "Bemerkung.1": None
    },
    {
        "Category": None,
        "Code": "K2022",
        "qs-STAT Pflicht-eingabe-felder": "X",
        "Schl\u00fcs-selfeld \nim upload": None,
        "Feldbezeichnung": "Nachkommast.",
        "Bemerkung": None,
        "Format-Vorgabe,\nBeispiele": None,
        "Standard allgemein": "Eintrag nach Bedarf",
        "Sonderkonfigurationen / Hinweise": None,
        "L\u00e4nge": 1,
        "Typ*": "I",
        "Eingabe": None,
        "Bemerkung.1": None
    },
    {
        "Category": None,
        "Code": "K2041",
        "qs-STAT Pflicht-eingabe-felder": None,
        "Schl\u00fcs-selfeld \nim upload": None,
        "Feldbezeichnung": "Erfassungsart",
        "Bemerkung": "Name der RS232 Schnittstelle",
        "Format-Vorgabe,\nBeispiele": None,
        "Standard allgemein": None,
        "Sonderkonfigurationen / Hinweise": None,
        "L\u00e4nge": 2,
        "Typ*": "I",
        "Eingabe": None,
        "Bemerkung.1": None
    },
    {
        "Category": None,
        "Code": "K2060",
        "qs-STAT Pflicht-eingabe-felder": None,
        "Schl\u00fcs-selfeld \nim upload": None,
        "Feldbezeichnung": "Ereigniskatalog",
        "Bemerkung": None,
        "Format-Vorgabe,\nBeispiele": None,
        "Standard allgemein": None,
        "Sonderkonfigurationen / Hinweise": None,
        "L\u00e4nge": 5,
        "Typ*": "I",
        "Eingabe": None,
        "Bemerkung.1": None
    },
    {
        "Category": None,
        "Code": "K2101",
        "qs-STAT Pflicht-eingabe-felder": None,
        "Schl\u00fcs-selfeld \nim upload": None,
        "Feldbezeichnung": "Nennma\u00df",
        "Bemerkung": "Kann eingetragen werden, wenn innerhalb der Toleranz",
        "Format-Vorgabe,\nBeispiele": None,
        "Standard allgemein": "Eintrag nach Bedarf",
        "Sonderkonfigurationen / Hinweise": None,
        "L\u00e4nge": 22,
        "Typ*": "F",
        "Eingabe": None,
        "Bemerkung.1": None
    },
    {
        "Category": None,
        "Code": "K2110",
        "qs-STAT Pflicht-eingabe-felder": "X",
        "Schl\u00fcs-selfeld \nim upload": None,
        "Feldbezeichnung": "Unt. Spez.Gr.",
        "Bemerkung": None,
        "Format-Vorgabe,\nBeispiele": None,
        "Standard allgemein": "Eintrag nach Bedarf",
        "Sonderkonfigurationen / Hinweise": None,
        "L\u00e4nge": 22,
        "Typ*": "F",
        "Eingabe": None,
        "Bemerkung.1": None
    },
    {
        "Category": None,
        "Code": "K2111",
        "qs-STAT Pflicht-eingabe-felder": "X",
        "Schl\u00fcs-selfeld \nim upload": None,
        "Feldbezeichnung": "Ob. Spez.Gr.",
        "Bemerkung": None,
        "Format-Vorgabe,\nBeispiele": None,
        "Standard allgemein": "Eintrag nach Bedarf",
        "Sonderkonfigurationen / Hinweise": None,
        "L\u00e4nge": 22,
        "Typ*": "F",
        "Eingabe": None,
        "Bemerkung.1": None
    },
    {
        "Category": None,
        "Code": "K2112",
        "qs-STAT Pflicht-eingabe-felder": "X",
        "Schl\u00fcs-selfeld \nim upload": None,
        "Feldbezeichnung": "unteres Abma\u00df",
        "Bemerkung": None,
        "Format-Vorgabe,\nBeispiele": None,
        "Standard allgemein": "Eintrag nach Bedarf",
        "Sonderkonfigurationen / Hinweise": None,
        "L\u00e4nge": 22,
        "Typ*": "F",
        "Eingabe": None,
        "Bemerkung.1": None
    },
    {
        "Category": None,
        "Code": "K2113",
        "qs-STAT Pflicht-eingabe-felder": "X",
        "Schl\u00fcs-selfeld \nim upload": None,
        "Feldbezeichnung": "oberes Abma\u00df",
        "Bemerkung": None,
        "Format-Vorgabe,\nBeispiele": None,
        "Standard allgemein": "Eintrag nach Bedarf",
        "Sonderkonfigurationen / Hinweise": None,
        "L\u00e4nge": 22,
        "Typ*": "F",
        "Eingabe": None,
        "Bemerkung.1": None
    },
    {
        "Category": None,
        "Code": "K2120",
        "qs-STAT Pflicht-eingabe-felder": "X",
        "Schl\u00fcs-selfeld \nim upload": None,
        "Feldbezeichnung": "Unt.nat.Grenze",
        "Bemerkung": None,
        "Format-Vorgabe,\nBeispiele": None,
        "Standard allgemein": "Eintrag nach Bedarf",
        "Sonderkonfigurationen / Hinweise": None,
        "L\u00e4nge": 1,
        "Typ*": "I",
        "Eingabe": None,
        "Bemerkung.1": None
    },
    {
        "Category": None,
        "Code": "K2121",
        "qs-STAT Pflicht-eingabe-felder": "X",
        "Schl\u00fcs-selfeld \nim upload": None,
        "Feldbezeichnung": "Ob.nat.Grenze",
        "Bemerkung": None,
        "Format-Vorgabe,\nBeispiele": None,
        "Standard allgemein": "Eintrag nach Bedarf",
        "Sonderkonfigurationen / Hinweise": None,
        "L\u00e4nge": 1,
        "Typ*": "I",
        "Eingabe": None,
        "Bemerkung.1": None
    },
    {
        "Category": None,
        "Code": "K2142",
        "qs-STAT Pflicht-eingabe-felder": "X",
        "Schl\u00fcs-selfeld \nim upload": None,
        "Feldbezeichnung": "Einheit",
        "Bemerkung": None,
        "Format-Vorgabe,\nBeispiele": None,
        "Standard allgemein": "Eintrag nach Bedarf",
        "Sonderkonfigurationen / Hinweise": None,
        "L\u00e4nge": 20,
        "Typ*": "A",
        "Eingabe": None,
        "Bemerkung.1": None
    },
    {
        "Category": None,
        "Code": "K2152",
        "qs-STAT Pflicht-eingabe-felder": None,
        "Schl\u00fcs-selfeld \nim upload": None,
        "Feldbezeichnung": "Toleranz",
        "Bemerkung": None,
        "Format-Vorgabe,\nBeispiele": None,
        "Standard allgemein": None,
        "Sonderkonfigurationen / Hinweise": None,
        "L\u00e4nge": 22,
        "Typ*": "F",
        "Eingabe": None,
        "Bemerkung.1": None
    },
    {
        "Category": None,
        "Code": "K2202",
        "qs-STAT Pflicht-eingabe-felder": None,
        "Schl\u00fcs-selfeld \nim upload": None,
        "Feldbezeichnung": "Aw.Typ",
        "Bemerkung": "Verfahren 1 - 5",
        "Format-Vorgabe,\nBeispiele": None,
        "Standard allgemein": None,
        "Sonderkonfigurationen / Hinweise": None,
        "L\u00e4nge": 1,
        "Typ*": "I",
        "Eingabe": None,
        "Bemerkung.1": None
    },
    {
        "Category": None,
        "Code": "K2211",
        "qs-STAT Pflicht-eingabe-felder": "X",
        "Schl\u00fcs-selfeld \nim upload": None,
        "Feldbezeichnung": "Nummer",
        "Bemerkung": "Einstellnormal",
        "Format-Vorgabe,\nBeispiele": "01, 02, 03, \u2026",
        "Standard allgemein": "zweistellig",
        "Sonderkonfigurationen / Hinweise": None,
        "L\u00e4nge": 40,
        "Typ*": "A",
        "Eingabe": "Fest",
        "Bemerkung.1": "Editierung muss m\u00f6glich sein"
    },
    {
        "Category": None,
        "Code": "K2212",
        "qs-STAT Pflicht-eingabe-felder": "X",
        "Schl\u00fcs-selfeld \nim upload": None,
        "Feldbezeichnung": "Bezeichnung",
        "Bemerkung": "Einstellnormal",
        "Format-Vorgabe,\nBeispiele": "LY4711P1",
        "Standard allgemein": "Pr\u00fcfmittel-Bez.",
        "Sonderkonfigurationen / Hinweise": None,
        "L\u00e4nge": 40,
        "Typ*": "A",
        "Eingabe": "Fest",
        "Bemerkung.1": "Editierung muss m\u00f6glich sein"
    },
    {
        "Category": None,
        "Code": "K2213",
        "qs-STAT Pflicht-eingabe-felder": "X",
        "Schl\u00fcs-selfeld \nim upload": None,
        "Feldbezeichnung": "Istwert",
        "Bemerkung": "Einstellnormal",
        "Format-Vorgabe,\nBeispiele": 1.569,
        "Standard allgemein": "Wert aus Kalibrierschein",
        "Sonderkonfigurationen / Hinweise": None,
        "L\u00e4nge": 22,
        "Typ*": "F",
        "Eingabe": "Fest",
        "Bemerkung.1": "Editierung muss m\u00f6glich sein"
    },
    {
        "Category": None,
        "Code": "K2222",
        "qs-STAT Pflicht-eingabe-felder": None,
        "Schl\u00fcs-selfeld \nim upload": None,
        "Feldbezeichnung": "Anz. Ref. Mess.",
        "Bemerkung": None,
        "Format-Vorgabe,\nBeispiele": None,
        "Standard allgemein": None,
        "Sonderkonfigurationen / Hinweise": None,
        "L\u00e4nge": 5,
        "Typ*": "I",
        "Eingabe": None,
        "Bemerkung.1": None
    },
    {
        "Category": None,
        "Code": "K2243",
        "qs-STAT Pflicht-eingabe-felder": None,
        "Schl\u00fcs-selfeld \nim upload": None,
        "Feldbezeichnung": "Zeichnung",
        "Bemerkung": None,
        "Format-Vorgabe,\nBeispiele": None,
        "Standard allgemein": None,
        "Sonderkonfigurationen / Hinweise": None,
        "L\u00e4nge": 80,
        "Typ*": "A",
        "Eingabe": None,
        "Bemerkung.1": None
    },
    {
        "Category": None,
        "Code": "K2303",
        "qs-STAT Pflicht-eingabe-felder": None,
        "Schl\u00fcs-selfeld \nim upload": None,
        "Feldbezeichnung": "Abt./Name",
        "Bemerkung": None,
        "Format-Vorgabe,\nBeispiele": None,
        "Standard allgemein": None,
        "Sonderkonfigurationen / Hinweise": None,
        "L\u00e4nge": 40,
        "Typ*": "A",
        "Eingabe": None,
        "Bemerkung.1": None
    },
    {
        "Category": None,
        "Code": "K2311",
        "qs-STAT Pflicht-eingabe-felder": None,
        "Schl\u00fcs-selfeld \nim upload": None,
        "Feldbezeichnung": "Arbeitsgang-Nr",
        "Bemerkung": None,
        "Format-Vorgabe,\nBeispiele": None,
        "Standard allgemein": None,
        "Sonderkonfigurationen / Hinweise": None,
        "L\u00e4nge": 20,
        "Typ*": "A",
        "Eingabe": None,
        "Bemerkung.1": None
    },
    {
        "Category": None,
        "Code": "K2312",
        "qs-STAT Pflicht-eingabe-felder": None,
        "Schl\u00fcs-selfeld \nim upload": None,
        "Feldbezeichnung": "Arbeitsgang-Bez",
        "Bemerkung": None,
        "Format-Vorgabe,\nBeispiele": None,
        "Standard allgemein": None,
        "Sonderkonfigurationen / Hinweise": None,
        "L\u00e4nge": 40,
        "Typ*": "A",
        "Eingabe": None,
        "Bemerkung.1": None
    },
    {
        "Category": None,
        "Code": "K2401",
        "qs-STAT Pflicht-eingabe-felder": "X",
        "Schl\u00fcs-selfeld \nim upload": None,
        "Feldbezeichnung": "Pr\u00fcfmittel-Nr",
        "Bemerkung": "Messmittelnummer",
        "Format-Vorgabe,\nBeispiele": None,
        "Standard allgemein": "04",
        "Sonderkonfigurationen / Hinweise": None,
        "L\u00e4nge": 40,
        "Typ*": "A",
        "Eingabe": "Fest",
        "Bemerkung.1": "Editierung muss m\u00f6glich sein"
    },
    {
        "Category": None,
        "Code": "K2402",
        "qs-STAT Pflicht-eingabe-felder": "X",
        "Schl\u00fcs-selfeld \nim upload": None,
        "Feldbezeichnung": "Pr\u00fcfmittel-Bez.",
        "Bemerkung": "m\u00f6gliche Wiederholung in der Merkmalsmaske",
        "Format-Vorgabe,\nBeispiele": None,
        "Standard allgemein": "JMR2P11",
        "Sonderkonfigurationen / Hinweise": None,
        "L\u00e4nge": 80,
        "Typ*": "A",
        "Eingabe": "Fest",
        "Bemerkung.1": "Editierung muss m\u00f6glich sein"
    },
    {
        "Category": None,
        "Code": "K2404",
        "qs-STAT Pflicht-eingabe-felder": None,
        "Schl\u00fcs-selfeld \nim upload": None,
        "Feldbezeichnung": "Aufl\u00f6sung",
        "Bemerkung": None,
        "Format-Vorgabe,\nBeispiele": None,
        "Standard allgemein": None,
        "Sonderkonfigurationen / Hinweise": None,
        "L\u00e4nge": 22,
        "Typ*": "F",
        "Eingabe": None,
        "Bemerkung.1": None
    },
    {
        "Category": None,
        "Code": "K2406",
        "qs-STAT Pflicht-eingabe-felder": None,
        "Schl\u00fcs-selfeld \nim upload": None,
        "Feldbezeichnung": "Pr\u00fcfmit.Herst.",
        "Bemerkung": None,
        "Format-Vorgabe,\nBeispiele": None,
        "Standard allgemein": None,
        "Sonderkonfigurationen / Hinweise": None,
        "L\u00e4nge": 40,
        "Typ*": "A",
        "Eingabe": None,
        "Bemerkung.1": None
    },
    {
        "Category": None,
        "Code": "K2410",
        "qs-STAT Pflicht-eingabe-felder": None,
        "Schl\u00fcs-selfeld \nim upload": None,
        "Feldbezeichnung": "Pr\u00fcfort",
        "Bemerkung": None,
        "Format-Vorgabe,\nBeispiele": None,
        "Standard allgemein": None,
        "Sonderkonfigurationen / Hinweise": None,
        "L\u00e4nge": 40,
        "Typ*": "A",
        "Eingabe": None,
        "Bemerkung.1": None
    },
    {
        "Category": None,
        "Code": "K2411",
        "qs-STAT Pflicht-eingabe-felder": None,
        "Schl\u00fcs-selfeld \nim upload": None,
        "Feldbezeichnung": "Datum",
        "Bemerkung": "Datum",
        "Format-Vorgabe,\nBeispiele": None,
        "Standard allgemein": None,
        "Sonderkonfigurationen / Hinweise": None,
        "L\u00e4nge": 40,
        "Typ*": "D",
        "Eingabe": None,
        "Bemerkung.1": None
    },
    {
        "Category": None,
        "Code": "K2501",
        "qs-STAT Pflicht-eingabe-felder": None,
        "Schl\u00fcs-selfeld \nim upload": None,
        "Feldbezeichnung": "Bema\u00dfungsattribut",
        "Bemerkung": None,
        "Format-Vorgabe,\nBeispiele": None,
        "Standard allgemein": None,
        "Sonderkonfigurationen / Hinweise": None,
        "L\u00e4nge": 1,
        "Typ*": "I",
        "Eingabe": None,
        "Bemerkung.1": None
    },
    {
        "Category": None,
        "Code": "K2630",
        "qs-STAT Pflicht-eingabe-felder": "X",
        "Schl\u00fcs-selfeld \nim upload": None,
        "Feldbezeichnung": "Kal.-unsicherh.",
        "Bemerkung": "Einstellnormal",
        "Format-Vorgabe,\nBeispiele": 0.002,
        "Standard allgemein": "Wert aus Kalibrierschein",
        "Sonderkonfigurationen / Hinweise": None,
        "L\u00e4nge": None,
        "Typ*": None,
        "Eingabe": "Fest",
        "Bemerkung.1": "Editierung muss m\u00f6glich sein"
    },
    {
        "Category": None,
        "Code": "K2802",
        "qs-STAT Pflicht-eingabe-felder": None,
        "Schl\u00fcs-selfeld \nim upload": None,
        "Feldbezeichnung": "Zusatztest",
        "Bemerkung": None,
        "Format-Vorgabe,\nBeispiele": None,
        "Standard allgemein": None,
        "Sonderkonfigurationen / Hinweise": None,
        "L\u00e4nge": None,
        "Typ*": None,
        "Eingabe": None,
        "Bemerkung.1": None
    },
    {
        "Category": None,
        "Code": "K2900",
        "qs-STAT Pflicht-eingabe-felder": None,
        "Schl\u00fcs-selfeld \nim upload": None,
        "Feldbezeichnung": "Bemerkung",
        "Bemerkung": None,
        "Format-Vorgabe,\nBeispiele": None,
        "Standard allgemein": None,
        "Sonderkonfigurationen / Hinweise": None,
        "L\u00e4nge": 255,
        "Typ*": "A",
        "Eingabe": None,
        "Bemerkung.1": None
    },
    {
        "Category": None,
        "Code": "K8500",
        "qs-STAT Pflicht-eingabe-felder": "X",
        "Schl\u00fcs-selfeld \nim upload": None,
        "Feldbezeichnung": "Stpr. Umfang",
        "Bemerkung": None,
        "Format-Vorgabe,\nBeispiele": 3,
        "Standard allgemein": "Messmaschinenbezogen",
        "Sonderkonfigurationen / Hinweise": None,
        "L\u00e4nge": None,
        "Typ*": None,
        "Eingabe": "Fest",
        "Bemerkung.1": "Editierung muss m\u00f6glich sein"
    },
    {
        "Category": None,
        "Code": "K8501",
        "qs-STAT Pflicht-eingabe-felder": "X",
        "Schl\u00fcs-selfeld \nim upload": None,
        "Feldbezeichnung": "Stichprobe",
        "Bemerkung": "0: fest\n1: gleitend",
        "Format-Vorgabe,\nBeispiele": 0,
        "Standard allgemein": "Messmaschinenbezogen",
        "Sonderkonfigurationen / Hinweise": None,
        "L\u00e4nge": 1,
        "Typ*": "I",
        "Eingabe": "Fest",
        "Bemerkung.1": "Editierung muss m\u00f6glich sein"
    },
    {
        "Category": None,
        "Code": "K8502",
        "qs-STAT Pflicht-eingabe-felder": None,
        "Schl\u00fcs-selfeld \nim upload": None,
        "Feldbezeichnung": "Stpr. Frequenz",
        "Bemerkung": "Text\naus Maske entfernen?",
        "Format-Vorgabe,\nBeispiele": None,
        "Standard allgemein": None,
        "Sonderkonfigurationen / Hinweise": "wurde aus Merkmalsmaske\nentfernt",
        "L\u00e4nge": 40,
        "Typ*": "A",
        "Eingabe": None,
        "Bemerkung.1": None
    },
    {
        "Category": None,
        "Code": "K8504",
        "qs-STAT Pflicht-eingabe-felder": None,
        "Schl\u00fcs-selfeld \nim upload": None,
        "Feldbezeichnung": "Stichprobenfh\u00e4ufigkeit",
        "Bemerkung": None,
        "Format-Vorgabe,\nBeispiele": None,
        "Standard allgemein": None,
        "Sonderkonfigurationen / Hinweise": None,
        "L\u00e4nge": None,
        "Typ*": None,
        "Eingabe": None,
        "Bemerkung.1": None
    },
    {
        "Category": "Katalogfelder",
        "Code": None,
        "qs-STAT Pflicht-eingabe-felder": "Zusatzdaten in der Wertemaske k\u00f6nnen \u00fcber Katalogeintr\u00e4ge verwaltet werden. Alle Eintr\u00e4ge in den Katalogen werden zentral bei FeP/QMM11 Funk, Schneider verwaltet.",
        "Schl\u00fcs-selfeld \nim upload": None,
        "Feldbezeichnung": None,
        "Bemerkung": None,
        "Format-Vorgabe,\nBeispiele": None,
        "Standard allgemein": None,
        "Sonderkonfigurationen / Hinweise": None,
        "L\u00e4nge": None,
        "Typ*": None,
        "Eingabe": None,
        "Bemerkung.1": None
    },
    {
        "Category": None,
        "Code": "K4030/0",
        "qs-STAT Pflicht-eingabe-felder": " ",
        "Schl\u00fcs-selfeld \nim upload": None,
        "Feldbezeichnung": "Auftragskatalog",
        "Bemerkung": "Bezeichnung des Haupt- / Subkatalogs\nK4030/1 Bezeichnung des 1. Subkatalogs",
        "Format-Vorgabe,\nBeispiele": "RS_STOTZ",
        "Standard allgemein": None,
        "Sonderkonfigurationen / Hinweise": None,
        "L\u00e4nge": 80,
        "Typ*": "A",
        "Eingabe": None,
        "Bemerkung.1": None
    },
    {
        "Category": None,
        "Code": "K4031",
        "qs-STAT Pflicht-eingabe-felder": None,
        "Schl\u00fcs-selfeld \nim upload": None,
        "Feldbezeichnung": "Zuordnung der Elemente des Hautkatalogs zum jeweiligen Subkatalog",
        "Bemerkung": "Beschreibt welches der Elemente des Hauptkatalogs im Subkatalog verwendet werden.",
        "Format-Vorgabe,\nBeispiele": 1,
        "Standard allgemein": None,
        "Sonderkonfigurationen / Hinweise": None,
        "L\u00e4nge": 5,
        "Typ*": "I",
        "Eingabe": None,
        "Bemerkung.1": None
    },
    {
        "Category": None,
        "Code": "K4032",
        "qs-STAT Pflicht-eingabe-felder": None,
        "Schl\u00fcs-selfeld \nim upload": None,
        "Feldbezeichnung": "Auftrag-Nummer",
        "Bemerkung": None,
        "Format-Vorgabe,\nBeispiele": 1,
        "Standard allgemein": None,
        "Sonderkonfigurationen / Hinweise": None,
        "L\u00e4nge": 20,
        "Typ*": "A",
        "Eingabe": None,
        "Bemerkung.1": None
    },
    {
        "Category": None,
        "Code": "K4033",
        "qs-STAT Pflicht-eingabe-felder": None,
        "Schl\u00fcs-selfeld \nim upload": None,
        "Feldbezeichnung": "Auftrag-Bezeichnung",
        "Bemerkung": "wird verwendet f\u00fcr Pr\u00fcfgrund \nSerie, Kalibriermessung, Sondermessung am RS_Stotz\nInhalt wird durch FeP/QMM11 verwaltet",
        "Format-Vorgabe,\nBeispiele": "Serie",
        "Standard allgemein": None,
        "Sonderkonfigurationen / Hinweise": None,
        "L\u00e4nge": 80,
        "Typ*": "A",
        "Eingabe": None,
        "Bemerkung.1": None
    },
    {
        "Category": None,
        "Code": "K4060",
        "qs-STAT Pflicht-eingabe-felder": None,
        "Schl\u00fcs-selfeld \nim upload": None,
        "Feldbezeichnung": "Maschinenkatalog",
        "Bemerkung": "Bezeichnung des Haupt- / Subkatalogs",
        "Format-Vorgabe,\nBeispiele": "RS_STOTZ",
        "Standard allgemein": None,
        "Sonderkonfigurationen / Hinweise": None,
        "L\u00e4nge": 80,
        "Typ*": "A",
        "Eingabe": None,
        "Bemerkung.1": None
    },
    {
        "Category": None,
        "Code": "K4061",
        "qs-STAT Pflicht-eingabe-felder": None,
        "Schl\u00fcs-selfeld \nim upload": None,
        "Feldbezeichnung": "Zuordnung der Elemente des Hautkatalogs zum jeweiligen Subkatalog",
        "Bemerkung": "Beschreibt welches der Elemente des Hauptkatalogs im Subkatalog verwendet werden.",
        "Format-Vorgabe,\nBeispiele": 1,
        "Standard allgemein": None,
        "Sonderkonfigurationen / Hinweise": None,
        "L\u00e4nge": 5,
        "Typ*": "I",
        "Eingabe": None,
        "Bemerkung.1": None
    },
    {
        "Category": None,
        "Code": "K4062",
        "qs-STAT Pflicht-eingabe-felder": None,
        "Schl\u00fcs-selfeld \nim upload": None,
        "Feldbezeichnung": "Maschinen-Nummer",
        "Bemerkung": None,
        "Format-Vorgabe,\nBeispiele": 1,
        "Standard allgemein": None,
        "Sonderkonfigurationen / Hinweise": None,
        "L\u00e4nge": 20,
        "Typ*": "A",
        "Eingabe": None,
        "Bemerkung.1": None
    },
    {
        "Category": None,
        "Code": "K4063",
        "qs-STAT Pflicht-eingabe-felder": None,
        "Schl\u00fcs-selfeld \nim upload": None,
        "Feldbezeichnung": "Maschinen-Bezeichnung",
        "Bemerkung": "wird f\u00fcr die Zuordnung der Pr\u00fcfpl\u00e4ne zu den Pr\u00fcfpl\u00e4tzen verwendet,\nhier: Junker_01 ist die erste Maschine im Katalog (K4063/1)\nInhalt wird durch FeP/QMM11 verwaltet",
        "Format-Vorgabe,\nBeispiele": "Junker_01",
        "Standard allgemein": None,
        "Sonderkonfigurationen / Hinweise": None,
        "L\u00e4nge": 80,
        "Typ*": "A",
        "Eingabe": None,
        "Bemerkung.1": None
    },
    {
        "Category": None,
        "Code": "K4070",
        "qs-STAT Pflicht-eingabe-felder": None,
        "Schl\u00fcs-selfeld \nim upload": None,
        "Feldbezeichnung": "Pr\u00fcfmittelkatalog",
        "Bemerkung": "Bezeichnung des Haupt- / Subkatalogs",
        "Format-Vorgabe,\nBeispiele": None,
        "Standard allgemein": None,
        "Sonderkonfigurationen / Hinweise": None,
        "L\u00e4nge": 80,
        "Typ*": "A",
        "Eingabe": None,
        "Bemerkung.1": None
    },
    {
        "Category": None,
        "Code": "K4703",
        "qs-STAT Pflicht-eingabe-felder": None,
        "Schl\u00fcs-selfeld \nim upload": None,
        "Feldbezeichnung": "Pr\u00fcfmittel-Bezeichnung",
        "Bemerkung": "wird zur Unterscheidung der individuellen Pr\u00fcfmittel verwendet\nInhalt wird durch FeP/QMM11 verwaltet",
        "Format-Vorgabe,\nBeispiele": "004_RS-Nanoscan_01",
        "Standard allgemein": None,
        "Sonderkonfigurationen / Hinweise": None,
        "L\u00e4nge": 80,
        "Typ*": "A",
        "Eingabe": None,
        "Bemerkung.1": None
    },
    {
        "Category": None,
        "Code": "K4090",
        "qs-STAT Pflicht-eingabe-felder": None,
        "Schl\u00fcs-selfeld \nim upload": None,
        "Feldbezeichnung": "Pr\u00fcferkatalog",
        "Bemerkung": "Bezeichnung des Haupt- / Subkatalogs",
        "Format-Vorgabe,\nBeispiele": "RS_STOTZ",
        "Standard allgemein": None,
        "Sonderkonfigurationen / Hinweise": None,
        "L\u00e4nge": 80,
        "Typ*": "A",
        "Eingabe": None,
        "Bemerkung.1": None
    },
    {
        "Category": None,
        "Code": "K4091",
        "qs-STAT Pflicht-eingabe-felder": None,
        "Schl\u00fcs-selfeld \nim upload": None,
        "Feldbezeichnung": "Zuordnung der Elemente des Hautkatalogs zum jeweiligen Subkatalog",
        "Bemerkung": "Beschreibt welches der Elemente des Hauptkatalogs im Subkatalog verwendet werden.",
        "Format-Vorgabe,\nBeispiele": 1,
        "Standard allgemein": None,
        "Sonderkonfigurationen / Hinweise": None,
        "L\u00e4nge": 5,
        "Typ*": "I",
        "Eingabe": None,
        "Bemerkung.1": None
    },
    {
        "Category": None,
        "Code": "K4092",
        "qs-STAT Pflicht-eingabe-felder": None,
        "Schl\u00fcs-selfeld \nim upload": None,
        "Feldbezeichnung": "Pr\u00fcfer-Nummer",
        "Bemerkung": "User-ID, falls vorhanden",
        "Format-Vorgabe,\nBeispiele": "xyz_1fe",
        "Standard allgemein": None,
        "Sonderkonfigurationen / Hinweise": None,
        "L\u00e4nge": 20,
        "Typ*": "A",
        "Eingabe": None,
        "Bemerkung.1": None
    },
    {
        "Category": None,
        "Code": "K4093",
        "qs-STAT Pflicht-eingabe-felder": None,
        "Schl\u00fcs-selfeld \nim upload": None,
        "Feldbezeichnung": "Pr\u00fcfer-Name",
        "Bemerkung": "Pr\u00fcfername",
        "Format-Vorgabe,\nBeispiele": "Mustermann, Max",
        "Standard allgemein": None,
        "Sonderkonfigurationen / Hinweise": None,
        "L\u00e4nge": 80,
        "Typ*": "A",
        "Eingabe": None,
        "Bemerkung.1": None
    },
    {
        "Category": None,
        "Code": "K4094",
        "qs-STAT Pflicht-eingabe-felder": None,
        "Schl\u00fcs-selfeld \nim upload": None,
        "Feldbezeichnung": "Pr\u00fcfer-Abteilung",
        "Bemerkung": "Werkstatt",
        "Format-Vorgabe,\nBeispiele": "W011xxx",
        "Standard allgemein": None,
        "Sonderkonfigurationen / Hinweise": None,
        "L\u00e4nge": 50,
        "Typ*": "A",
        "Eingabe": None,
        "Bemerkung.1": None
    },
    {
        "Category": None,
        "Code": "K4110",
        "qs-STAT Pflicht-eingabe-felder": None,
        "Schl\u00fcs-selfeld \nim upload": None,
        "Feldbezeichnung": "Erzeugniskatalog",
        "Bemerkung": "Bezeichnung des Haupt- / Subkatalogs",
        "Format-Vorgabe,\nBeispiele": None,
        "Standard allgemein": None,
        "Sonderkonfigurationen / Hinweise": None,
        "L\u00e4nge": 80,
        "Typ*": "A",
        "Eingabe": None,
        "Bemerkung.1": None
    },
    {
        "Category": None,
        "Code": "K4112",
        "qs-STAT Pflicht-eingabe-felder": None,
        "Schl\u00fcs-selfeld \nim upload": None,
        "Feldbezeichnung": "Erzeugnis-Nummer",
        "Bemerkung": "Pr\u00fcfplatz-Nummer",
        "Format-Vorgabe,\nBeispiele": 1,
        "Standard allgemein": None,
        "Sonderkonfigurationen / Hinweise": None,
        "L\u00e4nge": 20,
        "Typ*": "A",
        "Eingabe": None,
        "Bemerkung.1": None
    },
    {
        "Category": None,
        "Code": "K4113",
        "qs-STAT Pflicht-eingabe-felder": None,
        "Schl\u00fcs-selfeld \nim upload": None,
        "Feldbezeichnung": "Erzeugnis-Name",
        "Bemerkung": "Pr\u00fcfplatz Bezeichnung",
        "Format-Vorgabe,\nBeispiele": "001_RS-STOTZ",
        "Standard allgemein": None,
        "Sonderkonfigurationen / Hinweise": None,
        "L\u00e4nge": 80,
        "Typ*": "A",
        "Eingabe": None,
        "Bemerkung.1": None
    },
    {
        "Category": None,
        "Code": "K4220",
        "qs-STAT Pflicht-eingabe-felder": None,
        "Schl\u00fcs-selfeld \nim upload": None,
        "Feldbezeichnung": "Ereigniskatalog",
        "Bemerkung": "Bezeichnung des Haupt- / Subkatalogs\nwird im FeP als Ma\u00dfnahmenkatalog verwendet",
        "Format-Vorgabe,\nBeispiele": "RS_STOTZ",
        "Standard allgemein": None,
        "Sonderkonfigurationen / Hinweise": None,
        "L\u00e4nge": 80,
        "Typ*": "A",
        "Eingabe": None,
        "Bemerkung.1": None
    },
    {
        "Category": None,
        "Code": "K4221",
        "qs-STAT Pflicht-eingabe-felder": None,
        "Schl\u00fcs-selfeld \nim upload": None,
        "Feldbezeichnung": "Zuordnung der Elemente des Hautkatalogs zum jeweiligen Subkatalog",
        "Bemerkung": "Beschreibt welches der Elemente des Hauptkatalogs im Subkatalog verwendet werden.",
        "Format-Vorgabe,\nBeispiele": 1,
        "Standard allgemein": None,
        "Sonderkonfigurationen / Hinweise": None,
        "L\u00e4nge": 5,
        "Typ*": "I",
        "Eingabe": None,
        "Bemerkung.1": None
    },
    {
        "Category": None,
        "Code": "K4222",
        "qs-STAT Pflicht-eingabe-felder": None,
        "Schl\u00fcs-selfeld \nim upload": None,
        "Feldbezeichnung": "Ereignis-Nummer",
        "Bemerkung": None,
        "Format-Vorgabe,\nBeispiele": "M11",
        "Standard allgemein": None,
        "Sonderkonfigurationen / Hinweise": None,
        "L\u00e4nge": 20,
        "Typ*": "A",
        "Eingabe": None,
        "Bemerkung.1": None
    },
    {
        "Category": None,
        "Code": "K4223",
        "qs-STAT Pflicht-eingabe-felder": None,
        "Schl\u00fcs-selfeld \nim upload": None,
        "Feldbezeichnung": "Ereignistext",
        "Bemerkung": None,
        "Format-Vorgabe,\nBeispiele": "100% verlesen, i.O. Anteil abgeliefert",
        "Standard allgemein": None,
        "Sonderkonfigurationen / Hinweise": None,
        "L\u00e4nge": 80,
        "Typ*": "A",
        "Eingabe": None,
        "Bemerkung.1": None
    },
    {
        "Category": None,
        "Code": "K4250",
        "qs-STAT Pflicht-eingabe-felder": None,
        "Schl\u00fcs-selfeld \nim upload": None,
        "Feldbezeichnung": "Nestkatalog",
        "Bemerkung": "Bezeichnung des Haupt- / Subkatalogs",
        "Format-Vorgabe,\nBeispiele": "Beschichtungstisch_MSW_01",
        "Standard allgemein": None,
        "Sonderkonfigurationen / Hinweise": None,
        "L\u00e4nge": 80,
        "Typ*": "A",
        "Eingabe": None,
        "Bemerkung.1": None
    },
    {
        "Category": None,
        "Code": "K4251",
        "qs-STAT Pflicht-eingabe-felder": None,
        "Schl\u00fcs-selfeld \nim upload": None,
        "Feldbezeichnung": "Zuordnung der Elemente des Hautkatalogs zum jeweiligen Subkatalog",
        "Bemerkung": "Beschreibt welches der Elemente des Hauptkatalogs im Subkatalog verwendet werden.",
        "Format-Vorgabe,\nBeispiele": 11,
        "Standard allgemein": None,
        "Sonderkonfigurationen / Hinweise": None,
        "L\u00e4nge": 5,
        "Typ*": "I",
        "Eingabe": None,
        "Bemerkung.1": None
    },
    {
        "Category": None,
        "Code": "K4253",
        "qs-STAT Pflicht-eingabe-felder": None,
        "Schl\u00fcs-selfeld \nim upload": None,
        "Feldbezeichnung": "Nestbezeichnung",
        "Bemerkung": "Verwaltung der einezelnen Nestnummern in der Beschichtung",
        "Format-Vorgabe,\nBeispiele": "G055",
        "Standard allgemein": None,
        "Sonderkonfigurationen / Hinweise": None,
        "L\u00e4nge": 80,
        "Typ*": "A",
        "Eingabe": None,
        "Bemerkung.1": None
    },
    {
        "Category": None,
        "Code": None,
        "qs-STAT Pflicht-eingabe-felder": None,
        "Schl\u00fcs-selfeld \nim upload": None,
        "Feldbezeichnung": None,
        "Bemerkung": None,
        "Format-Vorgabe,\nBeispiele": None,
        "Standard allgemein": None,
        "Sonderkonfigurationen / Hinweise": None,
        "L\u00e4nge": None,
        "Typ*": None,
        "Eingabe": None,
        "Bemerkung.1": None
    },
    {
        "Category": None,
        "Code": None,
        "qs-STAT Pflicht-eingabe-felder": None,
        "Schl\u00fcs-selfeld \nim upload": None,
        "Feldbezeichnung": "*Legende:",
        "Bemerkung": None,
        "Format-Vorgabe,\nBeispiele": None,
        "Standard allgemein": None,
        "Sonderkonfigurationen / Hinweise": None,
        "L\u00e4nge": None,
        "Typ*": None,
        "Eingabe": None,
        "Bemerkung.1": None
    },
    {
        "Category": None,
        "Code": None,
        "qs-STAT Pflicht-eingabe-felder": None,
        "Schl\u00fcs-selfeld \nim upload": None,
        "Feldbezeichnung": "I",
        "Bemerkung": "Integer",
        "Format-Vorgabe,\nBeispiele": None,
        "Standard allgemein": None,
        "Sonderkonfigurationen / Hinweise": None,
        "L\u00e4nge": None,
        "Typ*": None,
        "Eingabe": None,
        "Bemerkung.1": None
    },
    {
        "Category": None,
        "Code": None,
        "qs-STAT Pflicht-eingabe-felder": None,
        "Schl\u00fcs-selfeld \nim upload": None,
        "Feldbezeichnung": "F",
        "Bemerkung": "Flie\u00dfkommazahl",
        "Format-Vorgabe,\nBeispiele": None,
        "Standard allgemein": None,
        "Sonderkonfigurationen / Hinweise": None,
        "L\u00e4nge": None,
        "Typ*": None,
        "Eingabe": None,
        "Bemerkung.1": None
    },
    {
        "Category": None,
        "Code": None,
        "qs-STAT Pflicht-eingabe-felder": None,
        "Schl\u00fcs-selfeld \nim upload": None,
        "Feldbezeichnung": "D",
        "Bemerkung": "Datum / Zeitformat",
        "Format-Vorgabe,\nBeispiele": None,
        "Standard allgemein": None,
        "Sonderkonfigurationen / Hinweise": None,
        "L\u00e4nge": None,
        "Typ*": None,
        "Eingabe": None,
        "Bemerkung.1": None
    },
    {
        "Category": None,
        "Code": None,
        "qs-STAT Pflicht-eingabe-felder": None,
        "Schl\u00fcs-selfeld \nim upload": None,
        "Feldbezeichnung": "A",
        "Bemerkung": "Alphanumerisch",
        "Format-Vorgabe,\nBeispiele": None,
        "Standard allgemein": None,
        "Sonderkonfigurationen / Hinweise": None,
        "L\u00e4nge": None,
        "Typ*": None,
        "Eingabe": None,
        "Bemerkung.1": None
    },
    {
        "Category": None,
        "Code": None,
        "qs-STAT Pflicht-eingabe-felder": None,
        "Schl\u00fcs-selfeld \nim upload": None,
        "Feldbezeichnung": "S",
        "Bemerkung": "besondere Codierung",
        "Format-Vorgabe,\nBeispiele": None,
        "Standard allgemein": None,
        "Sonderkonfigurationen / Hinweise": None,
        "L\u00e4nge": None,
        "Typ*": None,
        "Eingabe": None,
        "Bemerkung.1": None
    },
    {
        "Category": None,
        "Code": None,
        "qs-STAT Pflicht-eingabe-felder": None,
        "Schl\u00fcs-selfeld \nim upload": None,
        "Feldbezeichnung": None,
        "Bemerkung": None,
        "Format-Vorgabe,\nBeispiele": None,
        "Standard allgemein": None,
        "Sonderkonfigurationen / Hinweise": None,
        "L\u00e4nge": None,
        "Typ*": None,
        "Eingabe": None,
        "Bemerkung.1": None
    },
    {
        "Category": None,
        "Code": None,
        "qs-STAT Pflicht-eingabe-felder": None,
        "Schl\u00fcs-selfeld \nim upload": None,
        "Feldbezeichnung": None,
        "Bemerkung": "Pflichtfelder",
        "Format-Vorgabe,\nBeispiele": None,
        "Standard allgemein": None,
        "Sonderkonfigurationen / Hinweise": None,
        "L\u00e4nge": None,
        "Typ*": None,
        "Eingabe": None,
        "Bemerkung.1": None
    }
]

result = convert_json_to_dict(json_data)
print(result)